#!/usr/bin/env python

from current_sensor import CurrentSensorINA219Node
from template_rospy_pkg.util import config_utils

if __name__ == '__main__':
    ros_args, user_args = config_utils.parse_args()

    node = CurrentSensorINA219Node(ros_args["__name"],
                                   ros_args["__param_namespace"],
                                   ros_args["__package_path"],
                                   ros_args["__clear_params"] )

